### ISSUE TITLE
Vill inte byta direction

### ISSUE THREAD

**Issue by Schampen** [Schampen/slutprojekt-programmering#3]
Har du någon aning varför min variabel direction byter värde av sig själv.
När spelet startas får direction ett start värde som just nu är "right", när man trycker på någon av knapparna w,a,s eller d så byter den värde, jag vet att den byter värde då jag har kollat att den gör de genom att skriva ut dess värde med en system out meddelande på directions värde precis efter den ändrat och då var värdet ändrat.
Men efter det att värdet har ändras så byts den direkt tillbaka till dess startvärde "right", jag kan inte hitta varför den gör det jag hittar ingen stans i koden där jag sätter den till ett värde förutom när spelet startar eller när en av knapparna trycks

**Comment by MagnusSilverdal** [comment]
Lite lurigt att debugga men jag hittade det till slut. Det blir knas i kopplingen mellan de olika insatanserna av game.  Problemet är att du har två konstruktorer för SnakeGame. Den första används i main där en instans kallad game skapas. Men i den konstruktorn skapas sedan en ny instans som också kallas game. Då blir det knas och svårt att veta vilken av game som saker och ting refererar till. Jag löste det genom att flytta koden som ligger i den andra konstruktorn (SnakeGame()) till main och bara använda SnakeGame(int w, int h)). Det är fortafarande lite konstigt att man måste klicka i fönstret innan keylistenern svarar. Ett sätt att komma runt det är att lägga in en startskärm som man måste klicka på för att spelet ska gå igång. 
Fixa en enkel poängräknare och lägg in databaskopplingen så att du har alla delar.
